# - name: Make sure nginx is installed on correct system
#   hosts: nginx
#   gather_facts: no
#   remote_user: tomas
#   become: true
  # tasks:
- name: Make sure nginx is installed
  apt: name=nginx update_cache=yes state=latest

- name: Make sure nginx is started
  service:
    name: nginx
    state: started
    
- name: Wait for web to become available
  wait_for:
    port: 80

