- name: Destroy my lab
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    group: mytestgroup
  tasks:
  - name: Ensure resource group does not exist
    azure_rm_resourcegroup:
      name: "{{ group }}"
      location: westeurope
      state: absent
      force: true
